<?php 
/*
Plugin Name: TBL Firebase auth
Plugin URI: https://www.thomasiosprogrammer.com/
Description: TBL Firebase authentication with WordPress authentication.
Version: 0.0.1
Author: Thomas Woodfin
Author URI: https://www.thomasiosprogrammer.com/
Text Domain: tfa
Generated By: http://ensuredomains.com
*/

// If this file is called directly, abort. //
if ( ! defined( 'WPINC' ) ) {die;} // end if

// Let's Initialize Everything
if ( file_exists( plugin_dir_path( __FILE__ ) . 'core-init.php' ) ) {
require_once( plugin_dir_path( __FILE__ ) . 'core-init.php' );
}



// add_action('set_current_user', 'cc_hide_admin_bar');
function cc_hide_admin_bar() {
  if (!current_user_can('edit_posts')) {
    show_admin_bar(false);
  }
}